Add alerts endpoint
openrca/orca pull request #99
Opened 2020-07-29 05:57 UTC by aleksandra-galara

It implements (#98).

Signed-off-by: Aleksandra Galara <a.galara@samsung.com>

2020-07-29 06:40 UTC, aleksandra-galara commented
Payload example:

```
{
  "alerts": [
    {
      "id": "prometheus-alert-nodeclocknotsynchronising-node-192.168.122.250:9100",
      "origin": "prometheus",
      "properties": {
        "name": "NodeClockNotSynchronising",
        "kind": "node",
        "instance": "192.168.122.250:9100",
        "namespace": "{}",
        "message": "Clock on 192.168.122.250:9100 is not synchronising. Ensure NTP is configured on this host.",
        "severity": "warning"
      }
    },
    {
      "id": "prometheus-alert-kubecontainerwaiting-pod-test-1595997840-l848n-default",
      "origin": "prometheus",
      "properties": {
        "name": "KubeContainerWaiting",
        "kind": "pod",
        "instance": "test-1595997840-l848n",
        "namespace": "default",
        "message": "Pod default/test-1595997840-l848n container hello has been in waiting state for longer than 1 hour.",
        "severity": "warning"
      }
    }
  ]
}
```

2020-07-29 08:12 UTC, bzurkowski requested changes
@aleksandra-galara Thanks for the PR! 👍 I added some remarks to consider. Most of them are related to the payload structure. We must change it a little bit based on the discussion that we had yesterday with the UI team (some fields were missing). Also, the payload structure should be more flat to make it convenient for processing in the UI:

```json
{
    "id": "xyz",
    "origin": "prometheus",
    "name": "SomethingHorribleHappenedWithAPod",
    "message": "It's bad :(",
    "severity": "critical",
    "source": {
        "origin": "kubernetes",
        "kind": "pod",
        "properties": {
            "name": "elasticsearch",
            "namespace": "logging"
        }
    },
    "created_at": 123456789,
    "updated_at": 123456789
}
```

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/__init__.py
> +from orca.api.resources.v1 import alert as alerts_ns
Let's follow the convention and use the singular form: `alert_ns`.

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +def initialize(alerts):
The variable name `alerts` is a little bit misleading. Let's rename to `graph` since the `initialize` method takes a graph instance as its argument.

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +        'namespace': fields.String(attribute='properties.source_mapping.properties.namespace', default="n/a"),
Let's put the `source_mapping` fields into a nested `source` field in the alert payload:
```json
{
    "source": {
        "origin": "kubernetes",
        "kind": "pod",
        "properties": {
            "name": "elasticsearch",
            "namespace": "logging"
        }
    }
}
```
Also note that the source `origin` field is missing.

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +    'properties': {
Let's remove the nesting via the `properties` field and treat the alerts payload flat instead.

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +})
Let's add timestamp fields: `created_at`, `updated_at`.

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +    def __init__(self, api, alerts):
The variable name `alerts` is a little bit misleading. Let's rename to `graph` since the API constructor takes a graph instance as its argument.

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +node_fields = Model('Alert Node', {
`node_fields` is a left-over after the Graph API. Let's rename to `alert_fields`. We could also rename the `alerts_fields` (below) to `alert_list_fields`.

2020-07-29 08:12 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +            'nodes': self._alerts.get_nodes(kind='alert'),
I think we don't have to use the dict at this point. Instead, we should be able to directly pass the list of alert nodes to the `marshal` method. Try it out 😉

2020-07-29 12:37 UTC, aleksandra-galara commented
As for now, the payload looks like that:
```
[
  {
    "id": "prometheus-alert-nodeclocknotsynchronising-node-192.168.122.250:9100",
    "origin": "prometheus",
    "name": "NodeClockNotSynchronising",
    "message": "Clock on 192.168.122.250:9100 is not synchronising. Ensure NTP is configured on this host.",
    "severity": "warning",
    "source": {
      "origin": "kubernetes",
      "kind": "node",
      "properties": {
        "name": "192.168.122.250:9100",
        "namespace": "{}"
      }
    },
    "created_at": "1595996122",
    "updated_at": "1595996122"
  },
  {
    "id": "prometheus-alert-kubepodcrashlooping-pod-zabbix-server-rkw4p-zabbix",
    "origin": "prometheus",
    "name": "KubePodCrashLooping",
    "message": "Pod zabbix/zabbix-server-rkw4p (zabbix-server) is restarting 0.43 times / 5 minutes.",
    "severity": "critical",
    "source": {
      "origin": "kubernetes",
      "kind": "pod",
      "properties": {
        "name": "zabbix-server-rkw4p",
        "namespace": "zabbix"
      }
    },
    "created_at": "1595996124",
    "updated_at": "1596021884"
  }
]
```

2020-08-07 08:28 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +        self._alerts = graph
Let's call things by name. Graph is not an alert list. Why not just: `self._graph = graph`? 😃

2020-08-07 08:28 UTC, bzurkowski commented on orca/api/resources/v1/alert.py
> +        }
I'm wondering if we could refactor this a little bit by using the [Nested field](https://flask-restx.readthedocs.io/en/latest/marshalling.html#nested-field).

2020-08-17 20:26 UTC, bzurkowski approved these changes
@aleksandra-galara Thanks for the fixes. I wonder how the new endpoint operates with the new alerts dashboard in the UI 😉 Good work! 👍

2020-08-17 20:27 UTC, merged